name: 'dbt_snowflake_monitoring'
version: '5.0.4'
config-version: 2

profile: dbt_snowflake_monitoring

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  dbt_snowflake_monitoring:
    # The config below applies only when running this package directly as a project, not when installed as a package in another project.
    +on_schema_change: "append_new_columns"
    +query_tags: dbt_special

dispatch:
  - macro_namespace: dbt
    search_order:
      - dbt_snowflake_monitoring
      - dbt
query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.